FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/frontend/package*.json ./apps/frontend/
COPY apps/backend/package*.json ./apps/backend/
RUN npm install
COPY . .
WORKDIR /app/apps/frontend
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
